[package]
name = "ballista-integration-tests"
version = "0.3.0-alpha-1"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

[dependencies]
ballista = { path = "../../rust/ballista" }

tokio = { version = "0.2", features = ["full"] }
