[package]
name = "ballista-benchmarks"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"

[dependencies]
ballista = { path=".." }
arrow = "0.17"
arrow-flight = "0.17"
datafusion = "0.17"
clap = "2.33"
tokio = { version = "0.2", features = ["full"] }
