[package]
name = "ballista"
description = "Distributed compute platform based on Apache Arrow"
license = "Apache-2.0"
version = "0.3.0-SNAPSHOT"
homepage = "https://github.com/ballista-compute/ballista"
repository = "https://github.com/ballista-compute/ballista"
authors = ["Andy Grove <andygrove73@gmail.com>"]
edition = "2018"
build = "build.rs"
include = ["build.rs", "src/**/*", "Cargo.toml", "proto/ballista.proto"]

[dependencies]
env_logger = { version = "0.6", default-features = false }
futures = "0.3"
http = "0.1"
k8s-openapi = { version = "0.8.0", features = ["v1_13"] }
kube = "0.35"
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
tonic = "0.1.1"
fnv = "1.0.7"
flatbuffers = "0.6.0"
prost = "0.6"
prost-types = "0.6"
reqwest = "0.9.18"
uuid = { version = "0.8", features = ["serde", "v4"] }
sqlparser = "0.2.6"
crossbeam = "0.7"
smol = "0.1.18"
async-trait = "0.1.36"
random-fast-rng = "0.1.1"
structopt = "0.3"
etcd-client = "0.4"

# For local development and debugging
#arrow = { path = "../../../arrow/rust/arrow" }
#arrow-flight = { path = "../../../arrow/rust/arrow-flight" }
#datafusion = { path = "../../../arrow/rust/datafusion" }

# Ballista sometimes depends on this fork when PRs are still pending against Arrow repo
#arrow = { git = "https://github.com/andygrove/arrow", branch="ballista" }
#arrow-flight = { git = "https://github.com/andygrove/arrow", branch="ballista" }
#datafusion = { git = "https://github.com/andygrove/arrow", branch="ballista" }

# Ballista 0.3.0-SNAPSHOT depends on latest Arrow
arrow = { git = "https://github.com/apache/arrow" }
arrow-flight = { git = "https://github.com/apache/arrow" }
datafusion = { git = "https://github.com/apache/arrow" }
parquet = { git = "https://github.com/apache/arrow" }

# Ballista 0.3.x releases will depend on Arrow 1.0.0
#arrow = "1.0.0"
#arrow-flight = "1.0.0"
#datafusion = "1.0.0"

[[bin]]
name = "executor"
path = "src/bin/executor.rs"

[build-dependencies]
prost-build = { version = "0.6.1" }
