version: '2.0'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.9
    command: "etcd -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379"
    ports:
      - "2379:2379"
  ballista-rust:
    image: ballistacompute/ballista-rust:0.4.0-SNAPSHOT
    command: "/executor --mode etcd --etcd-urls etcd:2379 --external-host 0.0.0.0 --port 50051"
    ports:
      - "50051:50051"
    volumes:
      - ./data:/mnt/tpch
#  ballista-jvm:
#    image: ballistacompute/ballista-jvm:0.4.0-SNAPSHOT
#    ports:
#      - "50052:50051"
#    volumes:
#      - /mnt/nyctaxi:/mnt/nyctaxi
#  ballista-spark:
#    image: ballistacompute/ballista-spark:0.4.0-SNAPSHOT
#    ports:
#      - "50053:50051"
#    volumes:
#      - ./data:/mnt/tpch
