version: '2.0'
services:
  ballista-rust:
    image: ballistacompute/ballista-rust:0.3.0-SNAPSHOT
    ports:
      - "50051:50051"
    volumes:
      - /mnt/nyctaxi:/mnt/nyctaxi
  ballista-jvm:
    image: ballistacompute/ballista-jvm:0.3.0-SNAPSHOT
    ports:
      - "50052:50051"
    volumes:
      - /mnt/nyctaxi:/mnt/nyctaxi
  ballista-spark:
    image: ballistacompute/ballista-spark:0.3.0-SNAPSHOT
    ports:
      - "50053:50051"
    volumes:
      - /mnt/nyctaxi:/mnt/nyctaxi