name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Note, toolchain version must match the rustup version: either "nightly" or "nightly-YYYY-MM-DD"
# and must contain the toolchain for the OS at the end.

env:
  VCPKGRS_DYNAMIC: 1
  RUSTUP_VERSION: nightly-2020-05-14
  TOOLCHAIN_VERSION: nightly-2020-05-14-x86_64-pc-windows-msvc

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup default ${RUSTUP_VERSION} && rustup component add rustfmt clippy
    - name: Build Ballista
      run: cd rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Integration Tests
      run: cd integration-tests/rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Benchmarks
      run: cd benchmarks && cargo clippy -- -Dwarnings && cargo build
    - name: Run tests
      run: cd rust && cargo test

  Mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew install rustup
        rustup default ${RUSTUP_VERSION} && rustup component add rustfmt clippy
    - name: Build Ballista
      run: cd rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Integration Tests
      run: cd integration-tests/rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Benchmarks
      run: cd benchmarks && cargo clippy -- -Dwarnings && cargo build
    - name: Run tests
      run: cd rust && cargo test

  Windows:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: Prepare the Windows Build Environment
      run: |
        vcpkg update
        vcpkg integrate install
        vcpkg install openssl:x64-windows
    - name: Setup Rust Nightly
      run: |
        rustup default nightly-2020-05-14
        rustup toolchain install nightly-2020-05-14
        rustup component add rustfmt clippy --toolchain nightly-2020-05-14-x86_64-pc-windows-msvc
    - name: Build Ballista
      run: |
        cd rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Integration Tests
      run: |
        cd integration-tests/rust && cargo clippy -- -Dwarnings && cargo build
    - name: Build Becnhmarks
      run: |
        cd benchmarks && cargo clippy -- -Dwarnings && cargo build
    - name: Run tests
      run: |
        cd rust && cargo test
